import {QuestAncientCity} from "./zokor";
import {QuestBalacksCove} from "./balacksCove";
import {QuestBountifulBeanstalk} from "./bountifulBeanstalk";
import {QuestClawShotCity} from "./clawShotCity";
import {QuestDraconicDepths} from "./draconicDepths";
import {QuestFloatingIslands} from "./floatingIslands";
import {QuestForbiddenGrove} from "./forbiddenGrove";
import {QuestForewordFarm} from "./forewordFarm";
import {QuestFortRox} from "./fortRox";
import {QuestHalloweenBoilingCauldron} from "./halloween";
import {QuestHarbour} from "./harbour";
import {QuestIceberg} from "./iceberg";
import {QuestIceFortress} from "./iceFortress";
import {QuestLabyrinth} from "./labyrinth";
import {QuestLivingGarden} from "./livingGarden";
import {QuestLostCity} from "./lostCity";
import {QuestMousoleum} from "./mousoleum";
import {QuestMoussuPicchu} from "./moussuPicchu";
import {QuestPollutionOutbreak} from "./toxicSpill";
import {QuestQuesoGeyser} from "./quesoGeyser";
import {QuestRiftBristleWoods} from "./bristleWoodsRift";
import {QuestRiftBurroughs} from "./burroughsRift";
import {QuestRiftFuroma} from "./furomaRift";
import {QuestRiftValour} from "./valourRift";
import {QuestRiftWhiskerWoods} from "./whiskerWoodsRift";
import {QuestSandDunes} from "./sandDunes";
import {QuestSchoolOfSorcery} from "./schoolOfSorcery";
import {QuestSpringHunt} from "./springHunt";
import {QuestSunkenCity} from "./sunkenCity";
import {QuestSuperBrieFactory} from "./superBrieFactory";
import {QuestTableOfContents} from "./tableOfContents";
import {QuestTrainStation} from "./gnawnianExpressStation";

export interface Quests {
    QuestAncientCity?: QuestAncientCity; // Zokor
    QuestBalacksCove?: QuestBalacksCove;
    QuestBountifulBeanstalk?: QuestBountifulBeanstalk;
    QuestClawShotCity?: QuestClawShotCity;
    QuestDraconicDepths?: QuestDraconicDepths;
    QuestFloatingIslands?: QuestFloatingIslands;
    QuestForbiddenGrove?: QuestForbiddenGrove;
    QuestForewordFarm?: QuestForewordFarm;
    QuestFortRox?: QuestFortRox;
    QuestHarbour?: QuestHarbour;
    QuestHalloweenBoilingCauldron?: QuestHalloweenBoilingCauldron;
    QuestIceberg?: QuestIceberg;
    QuestIceFortress?: QuestIceFortress;
    QuestLabyrinth?: QuestLabyrinth;
    QuestLivingGarden?: QuestLivingGarden;
    QuestLostCity?: QuestLostCity;
    QuestMousoleum?: QuestMousoleum;
    QuestMoussuPicchu?: QuestMoussuPicchu;
    QuestPollutionOutbreak?: QuestPollutionOutbreak; // Toxic Spill
    QuestQuesoGeyser?: QuestQuesoGeyser;
    QuestRelicHunter?: unknown;
    QuestRiftBristleWoods?: QuestRiftBristleWoods;
    QuestRiftBurroughs?: QuestRiftBurroughs;
    QuestRiftFuroma?: QuestRiftFuroma;
    QuestRiftWhiskerWoods?: QuestRiftWhiskerWoods;
    QuestRiftValour?: QuestRiftValour;
    QuestSandDunes?: QuestSandDunes;
    QuestSchoolOfSorcery?: QuestSchoolOfSorcery;
    QuestSunkenCity?: QuestSunkenCity;
    QuestSuperBrieFactory?: QuestSuperBrieFactory;
    QuestSpringHunt?: QuestSpringHunt;
    QuestTableOfContents?: QuestTableOfContents;
    QuestTrainStation?: QuestTrainStation; // Gnawnian Express Station
    QuestWinterHunt2021?: unknown;
}

export * from './balacksCove';
export * from './bountifulBeanstalk';
export * from './bristleWoodsRift';
export * from './burroughsRift';
export * from './clawShotCity';
export * from './floatingIslands';
export * from './forbiddenGrove';
export * from './forewordFarm';
export * from './fortRox';
export * from './furomaRift';
export * from './gnawnianExpressStation';
export * from './halloween';
export * from './harbour';
export * from './iceberg';
export * from './iceFortress';
export * from './labyrinth';
export * from './livingGarden';
export * from './lostCity';
export * from './mousoleum';
export * from './moussuPicchu';
export * from './quesoGeyser';
export * from './sandDunes';
export * from './sunkenCity';
export * from './superBrieFactory';
export * from './tableOfContents';
export * from './schoolOfSorcery';
export * from './springHunt';
export * from './toxicSpill';
export * from './valourRift';
export * from './whiskerWoodsRift';
export * from './zokor';
